### ISSUE TITLE
Font-Awesome/Glyphicons not displaying in production

### ISSUE THREAD

**Issue by lukebrewerton** [dreamingechoes/adminlte-rails-template#2]
The icons do not display in production as it cannot find the font files. It looks for an incorrectly named file to load them.

i.e. `"GET /assets/back/font-awesome/fontawesome-webfont.woff2 HTTP/1.1" 404 1564 "https://site.com/assets/application_back-699a6d358ba3274ca416bfad917e5234901d74d20872684908d7a3fdeecd2a79.css"` but the `assets/back/` folder does not have any CSS named `application_back-699a6d358ba3274ca416bfad917e5234901d74d20872684908d7a3fdeecd2a79.css` or any files starting with this prefix.

**Comment by dreamingechoes** [comment]
Hi @lukebrewerton!

So weird, I've deployed this simple example to Heroku and it works ok for me. How are you doing the deployment process? Seems like the compilation of the assets isn't done properly 🤔

**Comment by lukebrewerton** [comment]
I have deployed it to an Nginx/Passenger server, going through the usual bundle exec assets:precompile etc and all the other CSS changes I have made are pulling through, conversely, it works fine when in the development environment

**Comment by dreamingechoes** [comment]
Ok, I'll check it again just in case and I'll let you know asap! 😄

**Comment by lukebrewerton** [comment]
Have you managed to reproduce this?

**Comment by lukebrewerton** [comment]
It seems that the assets precompile is appending a string to the filename but the main CSS calls the plain files

**Comment by dreamingechoes** [comment]
Hi @lukebrewerton!

I just pushed some commits changing the management of the assets a little bit, so could you update your test with the new changes and test if now works properly for you? If not is the case, please let me know.

Greetings! 😄

**Comment by lukebrewerton** [comment]
Hi @dreamingechoes,

That fixed it! It's now compiling all the assets correctly!
